# Generated by Django 4.0.6 on 2022-07-19 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0002_type_employe_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nombre')),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorias',
                'ordering': ['id'],
            },
        ),
        migrations.AlterField(
            model_name='employe',
            name='cvitae',
            field=models.FileField(upload_to='cvitae/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='type',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Nombre'),
        ),
        migrations.AddField(
            model_name='employe',
            name='categ',
            field=models.ManyToManyField(to='erp.category'),
        ),
    ]
