# Generated by Django 4.1.5 on 2023-02-12 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0003_auto_20230117_2337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='names',
            field=models.CharField(default='admin', max_length=150, verbose_name='Nombres'),
        ),
    ]
