# Generated by Django 4.0.6 on 2022-07-19 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0003_category_alter_employe_cvitae_alter_type_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='type',
            name='name',
            field=models.CharField(max_length=50, unique=True, verbose_name='Nombre'),
        ),
    ]
