# Generated by Django 4.0.6 on 2022-07-21 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0005_client_detsale_product_sale_delete_employe_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=150, unique=True, verbose_name='Nombre'),
        ),
    ]
