# Generated by Django 4.0.6 on 2022-07-26 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0006_alter_product_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='desc',
            field=models.CharField(default=2, max_length=150, verbose_name='Descripcion'),
            preserve_default=False,
        ),
    ]
