# Generated by Django 4.0.6 on 2022-07-26 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0007_category_desc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='desc',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Descripcion'),
        ),
    ]
