# Generated by Django 4.1 on 2022-08-20 00:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0013_alter_category_user_creation_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='birthday',
            new_name='date_birthday',
        ),
        migrations.RenameField(
            model_name='client',
            old_name='sexo',
            new_name='gender',
        ),
    ]
