# Generated by Django 4.1 on 2022-08-20 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0014_rename_birthday_client_date_birthday_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='dni',
            field=models.CharField(max_length=15, unique=True, verbose_name='Dni'),
        ),
    ]
